# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.kjson.org
date_format: "ordinal"
title: kjson
subtitle: "---------"
description: "kjson的个人博客"
keywords: kjson,博客,计算机,互联网,创业,时间管理,个人提升
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/kinjayson/kimjayson.github.io

# ---------------- #
#      Author      #
# ---------------- #
author: kjson
organization: Toutiao, Inc.
organization_url: https://www.toutiao.com
location: Beijing, China
email: i@kjson.org

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: kimjayson
douban_username: kimjayson
facebook_username: kimjayson
weibo_username: kimjayson
zhihu_username: kimjayson
twitter_username: kimjayson

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: kimjayson
disqus_username: kimjayson

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [C++, Python, Golang, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
popular_repos: ['kjson/linuxtools_rst','kjson/design_patterns', 'csdncommenter', 'kjson/design_patterns' ]
contribute_repos: ['']
